# make_python_dll_shims.ps1
#
# Generates python311.dll / python314.dll / python3.dll shims next to
# rustpython.exe, plus the rustpythonapi.dll relay they forward to.
#
# Extensions (.pyd) import the CPython DLL by name (e.g. python314.dll); the
# shims forward every symbol to rustpythonapi.dll, which re-exports the full
# RustPython C API of the *running* executable. Forwarding through a
# name-independent relay keeps all calls in the exe's module (sharing its
# thread-local VM) and works no matter what the interpreter exe is called:
# rustpython.exe, or the python.exe copy inside a venv.
#
# The relay (rustpythonapi.dll) contains:
#   - a jmp thunk per function symbol, jumping through a slot filled by
#     rustpythonapi_init() with the address of the process image's own export;
#   - real storage for the data symbols (the ~90 PyExc_* pointer slots and the
#     128-byte header stubs _Py_NoneStruct / PyUnicode_Type / PyLong_Type /
#     PyBool_Type), copied from the process image by rustpythonapi_init().
# The exe calls rustpythonapi_init(GetModuleHandle(NULL)) once, from
# crates/capi/src/objectstatics.rs (ensure_object_statics).
#
# Also generates import libraries: rustpython.lib (for the exe) and
# python311.lib / python314.lib / python3.lib (so .pyds can link against the
# shims).
#
# Usage:  powershell -File bench\make_python_dll_shims.ps1 [-TargetDir <dir>]
#
# Requires: a Visual Studio toolchain and a release build with the `capi`
# feature (default), which makes rustpython.exe export the C-API symbols.

param(
    [string]$TargetDir = ""
)

$ErrorActionPreference = "Stop"
$root = Split-Path -Parent $PSScriptRoot
if ($TargetDir -eq "") {
    $TargetDir = Join-Path $root "target\release"
}
$exe = Join-Path $TargetDir "rustpython.exe"
if (-not (Test-Path $exe)) {
    Write-Error "rustpython.exe not found in $TargetDir - run `cargo build --release` first"
}

# Locate MSVC tools.
$vsRoot = "C:\Program Files\Microsoft Visual Studio"
$vcvars = Get-ChildItem $vsRoot -Directory -ErrorAction SilentlyContinue |
    ForEach-Object { Get-ChildItem $_.FullName -Directory -ErrorAction SilentlyContinue } |
    ForEach-Object { Join-Path $_.FullName "VC\Auxiliary\Build\vcvars64.bat" } |
    Where-Object { Test-Path $_ } | Select-Object -First 1
if (-not $vcvars) {
    Write-Error "vcvars64.bat not found under $vsRoot"
}
$msvcBin = Get-ChildItem $vsRoot -Directory -ErrorAction SilentlyContinue |
    ForEach-Object { Get-ChildItem $_.FullName -Directory -ErrorAction SilentlyContinue } |
    ForEach-Object { Get-ChildItem (Join-Path $_.FullName "VC\Tools\MSVC") -Directory -ErrorAction SilentlyContinue } |
    Sort-Object Name -Descending | Select-Object -First 1
if (-not $msvcBin) {
    Write-Error "MSVC toolset not found"
}
$binDir = Join-Path $msvcBin.FullName "bin\Hostx64\x64"
$dumpbin = Join-Path $binDir "dumpbin.exe"
$libexe = Join-Path $binDir "lib.exe"
$ml64 = Join-Path $binDir "ml64.exe"
$cl = Join-Path $binDir "cl.exe"

# Run a command inside the VS developer environment.
function Invoke-VsEnv([string]$command) {
    cmd /c "call `"$vcvars`" >nul 2>&1 && $command"
}

# 1. Collect export names from rustpython.exe.
$exports = & $dumpbin /EXPORTS $exe | ForEach-Object {
    if ($_ -match '^\s+\d+\s+\w+\s+[0-9A-Fa-f]+\s+(\S+)\s*=\s*\S+\s*$') {
        $matches[1]
    }
} | Sort-Object -Unique
if (-not $exports) {
    Write-Error "no exports found in $exe (was it built with the capi feature?)"
}
Write-Host "relaying $($exports.Count) symbols from $exe"

# Classify symbols: data (needs real storage in the relay) vs functions
# (jmp thunks through slots). Keep in sync with crates/capi/src/objectstatics.rs.
$data128 = @('_Py_NoneStruct', 'PyUnicode_Type', 'PyLong_Type', 'PyBool_Type')
$data8 = @($exports | Where-Object { $_ -match '^PyExc_' })
$functions = @($exports | Where-Object { $_ -notin $data128 -and $_ -notin $data8 })
Write-Host "  functions: $($functions.Count), PyExc_* data: $($data8.Count), header stubs: $($data128.Count)"

# 2. Import library for the exe (used by the relay and by embedders).
$exeDef = Join-Path $TargetDir "rustpython.def"
$exeDefLines = @("LIBRARY rustpython", "EXPORTS")
foreach ($name in $exports) {
    $exeDefLines += "    $name"
}
Set-Content -Path $exeDef -Value $exeDefLines -Encoding Ascii
& $libexe /nologo "/def:$exeDef" "/out:$(Join-Path $TargetDir 'rustpython.lib')" /machine:x64
if ($LASTEXITCODE -ne 0) { throw "lib.exe failed for rustpython.lib" }

# 3. Build the relay DLL (rustpythonapi.dll).
$asmFile = Join-Path $TargetDir "relay.asm"
$cFile = Join-Path $TargetDir "relay.c"
$defFile = Join-Path $TargetDir "relay.def"

$asm = @("; generated by make_python_dll_shims.ps1", ".data")
foreach ($fn in $functions) {
    $asm += "slot_$fn QWORD ?"
}
foreach ($fn in $functions) {
    $asm += "PUBLIC slot_$fn"
}
$asm += ".code"
foreach ($fn in $functions) {
    $asm += "$fn PROC", "    jmp QWORD PTR [slot_$fn]", "$fn ENDP"
}
$asm += "END"
Set-Content -Path $asmFile -Value $asm -Encoding Ascii

$c = @("/* generated by make_python_dll_shims.ps1 */", "#include <windows.h>")
foreach ($name in $data128) {
    $c += "unsigned char $name[128];"
}
foreach ($name in $data8) {
    $c += "void *$name;"
}
foreach ($fn in $functions) {
    $c += "extern void *slot_$fn;"
}
$c += @(
    "",
    "/* Fill slots/data from the running executable (whatever its file name). */",
    "int rustpythonapi_init(void *exe) {",
    "    HMODULE h = (HMODULE)exe;",
    "    FARPROC p;"
)
foreach ($fn in $functions) {
    $c += "    slot_$fn = (void*)GetProcAddress(h, `"$fn`");"
}
foreach ($name in $data128) {
    $c += "    p = GetProcAddress(h, `"$name`"); if (p) { unsigned char *s = (unsigned char*)p; for (int i = 0; i < 128; i++) $name[i] = s[i]; }"
}
foreach ($name in $data8) {
    $c += "    p = GetProcAddress(h, `"$name`"); if (p) $name = *(void**)p;"
}
$c += "    return 1;", "}", "", "/* Self-initialize when the loader resolves python314.dll's forwards", "   (the exe also re-calls rustpythonapi_init after its statics are filled). */", "BOOL WINAPI DllMain(HINSTANCE hinst, DWORD reason, LPVOID reserved) {", "    (void)hinst; (void)reserved;", "    if (reason == DLL_PROCESS_ATTACH) {", "        rustpythonapi_init(GetModuleHandleW(NULL));", "    }", "    return TRUE;", "}"
Set-Content -Path $cFile -Value $c -Encoding Ascii

$defLines = @("LIBRARY rustpythonapi", "EXPORTS", "    rustpythonapi_init")
foreach ($name in $exports) {
    $defLines += "    $name"
}
Set-Content -Path $defFile -Value $defLines -Encoding Ascii

$relayOut = Join-Path $TargetDir "rustpythonapi.dll"
# This toolchain's ml64 ignores /Fo and writes "<input basename>.obj", so the
# asm is copied to a uniquely named file and its default output is used.
$relayAsm = Join-Path $TargetDir "relay_thunks.asm"
$relayAsmObj = Join-Path $TargetDir "relay_thunks.obj"
Copy-Item $asmFile $relayAsm -Force
$clOut = Invoke-VsEnv "cd /d `"$TargetDir`" && `"$cl`" /nologo /c /O2 /GS- relay.c /Forelay.obj 2>&1"
if (-not (Test-Path (Join-Path $TargetDir "relay.obj"))) {
    $clOut | Select-Object -Last 8
    throw "cl.exe failed for relay.c"
}
$mlOut = Invoke-VsEnv "cd /d `"$TargetDir`" && `"$ml64`" /nologo /c relay_thunks.asm 2>&1"
if (-not (Test-Path $relayAsmObj)) {
    $mlOut | Select-Object -Last 8
    throw "ml64 failed for relay_thunks.asm"
}
$linkOut = Invoke-VsEnv "cd /d `"$TargetDir`" && link /nologo /dll /entry:DllMain /def:`"$defFile`" relay.obj relay_thunks.obj kernel32.lib /out:`"$relayOut`" /machine:x64 2>&1"
if (-not (Test-Path $relayOut)) {
    $linkOut | Select-Object -Last 10
    throw "failed to build rustpythonapi.dll"
}
Write-Host "created $relayOut"

# 4. Forwarder shims + their import libs.
foreach ($dllName in @("python311", "python314", "python3")) {
    $def = Join-Path $TargetDir "$dllName.def"
    $lines = @("LIBRARY $dllName", "EXPORTS")
    foreach ($name in $exports) {
        $lines += "    $name = rustpythonapi.dll.$name"
    }
    Set-Content -Path $def -Value $lines -Encoding Ascii

    # The forwarding DLL itself (no code: every export forwards to the relay).
    $outDll = Join-Path $TargetDir "$dllName.dll"
    $linkCmd = "link /nologo /dll /noentry /def:$def /out:$outDll /machine:x64 /LIBPATH:$TargetDir"
    $linkOut = Invoke-VsEnv "$linkCmd 2>&1"
    if ($LASTEXITCODE -ne 0) {
        $linkOut | Select-Object -Last 10
        throw "link.exe failed for $dllName"
    }
    Write-Host "created $outDll"

    # Import library so .pyds can be linked against the shim.
    $plainDef = Join-Path $TargetDir "$dllName-plain.def"
    $plainLines = @("LIBRARY $dllName", "EXPORTS")
    foreach ($name in $exports) {
        $plainLines += "    $name"
    }
    Set-Content -Path $plainDef -Value $plainLines -Encoding Ascii
    & $libexe /nologo "/def:$plainDef" "/out:$(Join-Path $TargetDir "$dllName.lib")" /machine:x64
    if ($LASTEXITCODE -ne 0) { throw "lib.exe failed for $dllName.lib" }
    Write-Host "created $(Join-Path $TargetDir "$dllName.lib")"
}

# 5. Sanity checks.
$check = & $dumpbin /EXPORTS (Join-Path $TargetDir "python311.dll") |
    Select-String "PyModule_Create|PyArg_ParseTuple"
Write-Host "sanity: python311.dll exports:"
$check | Select-Object -First 4
$relayCheck = & $dumpbin /EXPORTS $relayOut | Select-String "PyArg_ParseTuple|rustpythonapi_init"
Write-Host "sanity: rustpythonapi.dll exports:"
$relayCheck | Select-Object -First 3
